on:
 schedule:
   - cron: '30 16 * * *'
 push:
   branches: [main, master]

name: Scrape NBA matchs

jobs:
  render:
    name: Scrape NBA matchs
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'

      # Set-up R
      - name: Install winaRaque package
        run: |
          R -e 'install.packages("devtools")'
          R -e 'devtools::install()'

      - name: Scrape the data
        run: Rscript exec/nba_matchs.R

      - name: Update README
        run: |
          R -e 'devtools::build_readme()'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Add nba matchs in data'
          git push origin main
