on:
  schedule:
    - cron: '30 17 * * *'
  push:
    branches: main

name: Scrape NBA matchs

jobs:
  render:
    name: Scrape NBA matchs
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      # Set-up R
      - name: Install packages
        run: Rscript -e 'install.packages(c("devtools","rvest","dplyr","plyr","xml2","jsonlite"))'

      - name: Scrape the data
        run: Rscript exec/nba_matchs.R

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Add nba matchs in data'
          git push origin main
