on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches: main

name: Scrape NBA matchs

jobs:
  render:
    name: Scrape NBA matchs
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      # Set-up R
      - name: Install packages
        run: Rscript -e 'install.packages(c("devtools","rvest","dplyr","plyr","xml2","jsonlite"))'

      - name: Scrape the data
        run: Rscript exec/nba_matchs.R

      - name: Commit results
        run: |
          git add -A
          git commit -m 'Add nba matchs in data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
