on:
  schedule:
    - cron: '00 18 * * *'
  push:
    branches: main

name: Scrape NBA matchs

jobs:
  render:
    name: Scrape NBA matchs
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      # Set-up R
      - name: Install packages
        run: Rscript -e 'install.packages(c("devtools","rvest","dplyr","plyr","xml2","jsonlite"))'

      - name: Scrape the data
        run: Rscript exec/nba_matchs.R

      - name: Commit results
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m 'Add nba matchs in data'
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
